### ISSUE TITLE
0.66 * NCAV function <> 0.66 * ( AssetsCurrent - Liabilities )

### ISSUE THREAD

**Issue by StephaneDHollander** [risenhoover/fintel-issues#12]
Can you tell me how the NCAV function is calculated? 

When I compare in the results of the sample
0.66 * (AssetsCurrent - Liabilities)> MarketCap  
with
0.66 * Ncav > MarketCap

I do not get the same results.
Stéphane D'Hollander

**Comment by risenhoover** [comment]
I made an adjustment to the calc - please check it again and let me know what you see.
