### ISSUE TITLE
Ticker: MBOT Current Ownership data not up-to-date

### ISSUE THREAD

**Issue by sunada777** [risenhoover/fintel-issues#16]
Current Ownership data for MBOT is not up-to-date.  Please rectify this issue to correctly display the latest 13f filings for this company.

Sincerely,

**Comment by risenhoover** [comment]
Is this still an issue?

**Comment by sunada777** [comment]
Yes, looks like MBOT data is mixed up with STEM data.  You have to see STEM to see MBOT's filings.  STEM doesn't exist anymore after the buyout.  MBOT is a different company.  Many investors rely on Fintel for latest filings, and I notice a lot of misinformation on forums due to this issue.  Thanks for you attention.

**Comment by risenhoover** [comment]
As you properly pointed out, this was due to a recent acquisition. I have adjusted the cusips and the lineage data appropriately. See https://fintel.io/so/us/mbot for more information. Thanks for pointing this out.

**Comment by risenhoover** [comment]
Thanks again for reporting this and if you find others that need fixing, please report them in the new message board https://fintel.io/g/welcome - since I don't check this github project very often I am going to retire it as an issue tracker. Thanks again.
