### ISSUE TITLE
Screener Produces Erroneous Results When Terms is Capitalized Differently

### ISSUE THREAD

**Issue by acemanhattan** [risenhoover/fintel-issues#18]
Consider the following screen:
( AssetsCurrent-Liabilities ) * 0.66 > MarketCap;
marketcap;
MaRkEtCaP;
Price;

Exchange | Symbol | Company | Assets Current | Liabilities | Market Cap | marketcap | Ma Rk Et Ca P
NASDAQ | XGTIW | XG Technology, Inc. | 33.46 | 16.71 | 2.16 | 39.92 | 46.24 

The result shows that the screener is sensitive to capitalization.

**Comment by risenhoover** [comment]
This was quite a find and thanks for pointing it out. The root cause was due to case sensitivity in the caching system. This should be resolved now. Sorry for taking so to see this. I'm moving all future bug reports to the new message board -> https://fintel.io/g/welcome - thanks.
