### ISSUE TITLE
Liquid Media Group (Nasdaq: YVR) public filings showing up in LBIX profile on Fintel.io

### ISSUE THREAD

**Issue by PGforLiquidMedia** [risenhoover/fintel-issues#34]
Dear Technical Team for Fintel.io: 

I am writing about errors appearing on Fintel.io for **Liquid Media Group Ltd. (NASDAQ: YVR).**  

Liquid's profile on Fintel.io: is: https://fintel.io/s/us/yvr .

In connection to this issue is data that is currently appearing on LBIX / Leading Brands Inc. (52170U207): https://fintel.io/s/us/lbix .

**Summary of defects:**

Please be advised that:  
1) Listings / indexing of current Liquid Media **news releases and public filings are appearing under the entry** ([profile](https://fintel.io/filings/us/lbix)) for  **Leading Brands Inc.** (Nasdaq: LBIX), the previous public entity and stock symbol (this change occurred on [August 9, 2018](http://www.globenewswire.com/news-release/2018/08/09/1549666/0/en/Leading-Brands-and-Liquid-Media-Group-Announce-Closing-of-Arrangement.html)).  The Leading Brands entry should no longer exist.

**Note:** Please see the [attached screen capture](https://user-images.githubusercontent.com/58082560/69447521-b4b58480-0d24-11ea-9d20-40bf2ffc89fe.png) of the LBIX / Leading Brands profile, which shows the Liquid Media filings (starting Aug. 2018) are listed here. I have circled the indicators in the first few entries.

2) At present, a [search ](https://fintel.io/s/us/yvr)on Fintel.io of Liquid Media / YVR i**s not pointing its public filings to this profile**, but generating a general web search that includes information unrelated to the company (e.g. the Vancouver Airport). 

**Action needed:**

Please kindly update your records to correctly present the Liquid Media profile on Fintel.io (e.g. as YVR / Liquid Media Group Ltd. (53634Q204) ), integrating public filings, news, data, etc. for the current public entity, and making any re-labeling corrections to  Leading Brands for entries that occurred on or after August 9, 2019.

Please advise if you have any questions or require more information.

I look forward to your **reply / update**.

**Supporting / Reference Information:**

If needed, enclosed is the following reference information for Liquid Media and when it commenced as a publicly traded company.

Liquid Media Group Ltd. (NASDAQ: YVR). 
Web: https://liquidmediagroup.co/ | CUSUP: 53634Q204

SEDAR Filings: Liquid Media Group Ltd. (formerly Leading Brands, Inc.) 
https://sedar.com/DisplayProfile.do?lang=EN&issuerType=03&issuerNo=00005446

SEC / EDGAR Filings: Liquid Media Group Ltd. 
https://www.sec.gov/cgi-bin/browse-edgar?CIK=YVR&owner=exclude&action=getcompany

Press release announcing the change in public entity:
Aug. 09, 2018: Leading Brands and Liquid Media Group Announce Closing of Arrangement
http://www.globenewswire.com/news-release/2018/08/09/1549666/0/en/Leading-Brands-and-Liquid-Media-Group-Announce-Closing-of-Arrangement.html

Press release - Commencement of trading as YVR
Aug. 13, 2018: Liquid Media Group Ltd. to Begin Trading on Nasdaq as YVR
http://www.globenewswire.com/news-release/2018/08/13/1550784/0/en/Liquid-Media-Group-Ltd-to-Begin-Trading-on-Nasdaq-as-YVR.html

Press release - Update of CUSIP to 53634Q204
Oct. 15, 2018: Liquid Media Group Effects 1-for-5 Reverse Stock Split per Listing Compliance Plan
http://www.globenewswire.com/news-release/2018/10/15/1621255/0/en/Liquid-Media-Group-Effects-1-for-5-Reverse-Stock-Split-per-Listing-Compliance-Plan.html

![2019-11-22-YVR-Fintel io-LBIX-SC2](https://user-images.githubusercontent.com/58082560/69447521-b4b58480-0d24-11ea-9d20-40bf2ffc89fe.png)

**Comment by risenhoover** [comment]
This is resolved
