### ISSUE TITLE
Calculation of Enterprise Value is incorrect

### ISSUE THREAD

**Issue by datawisely** [risenhoover/fintel-issues#4]
https://fintel.io/screen/negative-enterprise-value-companies

The calculation of the Enterprise Value is incorrect. It does not add Debt. Here ist the correct formula:

https://en.wikipedia.org/wiki/Enterprise_value

As a result the EV of NYSE:UIS is wrongly calculated with $19.5M - the correct calculation is here: https://www.gurufocus.com/term/ev/UIS/Enterprise+Value/Unisys+Corp and is $487M.

**Comment by risenhoover** [comment]
My initial investigation shows the calculation is coded correctly but it's pulling data from the most recent annual report, not the most recent quarterly report. I will update the code to use the most recent quarterly report and then continue auditing. Thanks for reporting this.

**Comment by risenhoover** [comment]
I have updated code to use MRQ data for calculating valuation metrics such as EV, NCAV, and so on.  EV for UIS is now $477M, which is more in line with other sources (see https://fintel.io/sm/us/uis ). However, both Yahoo and YCharts are reporting EV = $48xM so there is still a slight discrepancy that I will continue investigating.
