### ISSUE TITLE
Upload does not work

### ISSUE THREAD

**Issue by kelvinq** [risenhoover/fintel-issues#9]
Gives a vague error - 

`Oops, an error occurred

This exception has been logged with id XXXX. `

Tried with different browsers and different CSVs from Google Finance. No joy.

**Comment by risenhoover** [comment]
Thank you - I will look into this.

**Comment by risenhoover** [comment]
I made some adjustments, please try it again and update me.

**Comment by kelvinq** [comment]
Nope. Same error as before.

Reach out to me at kelvin@quee.org <mailto:kelvin@quee.org> and I will send you my CSV privately to help troubleshoot.


Kelvin
